# The service of mvp
apiVersion: v1
kind: Service
metadata:
  name: demo-svc
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    deploy: demo